site_name: Coffee Machine Documentation
site_description: Documentation for the Raspberry Pi-based coffee machine interface system
site_author: Thomas Petit-Jean
site_url: https://thomzoy.github.io/coffee

repo_name: Thomzoy/coffee
repo_url: https://github.com/Thomzoy/coffee

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: brown
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: brown
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: sphinx
            members_order: source
            show_source: true
            show_bases: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - User Guide:
    - Main principles: user-guide/principles.md
    - Possible LCD pages: user-guide/pages.md
    - Workflow: user-guide/workflow.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Setup:
    - Hardware Setup: setup/hardware-setup.md
    - Installation: setup/installation.md
  - Architecture:
    - Components: architecture/components.md
    - Application: architecture/application.md
  - API Reference:
    - App Module: api/app.md
    - IO Module: api/io.md
    - Configuration: api/config.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Thomzoy/coffee